name: flutter_listview_rest
description: Example on how to populate a ListView with data from a REST API
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter:
  google_map_polyline:
  permission:
  geolocator: ^5.1.4+2
  location: ^2.3.5
  google_maps_webservice: ^0.0.6
  flutter_polyline_points: ^0.1.0
  provider: ^4.3.1
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


assets:
  - assets/